[2024-12-16T18:31:38.388+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:31:38.391+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:31:38.395+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:31:38.394+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:31:38.430+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:31:38.413+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:31:38.431+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:31:38.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.174 seconds
[2024-12-16T18:32:09.288+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:32:09.289+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:32:09.289+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:32:09.289+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:32:09.293+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:32:09.292+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:32:09.293+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:32:09.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.039 seconds
[2024-12-16T18:33:23.180+0000] {processor.py:157} INFO - Started process (PID=28) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:33:23.184+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:33:23.184+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:33:23.184+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:33:23.196+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:33:23.192+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:33:23.197+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:33:23.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.134 seconds
[2024-12-16T18:33:53.874+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:33:53.875+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:33:53.876+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:33:53.876+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:33:53.884+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:33:53.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:33:53.884+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:33:53.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.026 seconds
[2024-12-16T18:34:24.446+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:34:24.446+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:34:24.447+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:34:24.447+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:34:24.451+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:34:24.450+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:34:24.452+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:34:24.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.023 seconds
[2024-12-16T18:34:55.197+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:34:55.197+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:34:55.198+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:34:55.198+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:34:55.202+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:34:55.201+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:34:55.202+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:34:55.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.020 seconds
[2024-12-16T18:35:25.915+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:35:25.916+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:35:25.917+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:35:25.917+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:35:25.921+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:35:25.920+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:35:25.921+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:35:25.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.019 seconds
[2024-12-16T18:35:56.681+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:35:56.682+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:35:56.682+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:35:56.682+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:35:56.686+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:35:56.685+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:35:56.687+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:35:56.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.021 seconds
[2024-12-16T18:36:27.558+0000] {processor.py:157} INFO - Started process (PID=88) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:36:27.558+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:36:27.559+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:36:27.559+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:36:27.563+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:36:27.562+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:36:27.563+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:36:27.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.024 seconds
[2024-12-16T18:36:58.272+0000] {processor.py:157} INFO - Started process (PID=98) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:36:58.273+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:36:58.273+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:36:58.273+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:36:58.278+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:36:58.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:36:58.279+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:36:58.291+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.022 seconds
[2024-12-16T18:37:29.066+0000] {processor.py:157} INFO - Started process (PID=108) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:37:29.067+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:37:29.068+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:37:29.068+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:37:29.072+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:37:29.071+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:37:29.072+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:37:29.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.022 seconds
[2024-12-16T18:38:00.115+0000] {processor.py:157} INFO - Started process (PID=118) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:38:00.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:38:00.116+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:38:00.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:38:00.119+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:38:00.118+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:38:00.120+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:38:00.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.019 seconds
[2024-12-16T18:38:30.966+0000] {processor.py:157} INFO - Started process (PID=128) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:38:30.966+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:38:30.967+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:38:30.967+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:38:30.972+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:38:30.971+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:38:30.972+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:38:30.986+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.022 seconds
[2024-12-16T18:39:01.748+0000] {processor.py:157} INFO - Started process (PID=138) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:39:01.750+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:39:01.751+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:39:01.750+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:39:01.755+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:39:01.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:39:01.756+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:39:01.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.027 seconds
[2024-12-16T18:39:32.518+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:39:32.519+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:39:32.520+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:39:32.520+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:39:32.524+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:39:32.524+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:39:32.525+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:39:32.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.029 seconds
[2024-12-16T18:40:03.260+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:40:03.261+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:40:03.261+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:40:03.261+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:40:03.265+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:40:03.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:40:03.265+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:40:03.289+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.031 seconds
[2024-12-16T18:43:35.184+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:43:35.188+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:43:35.198+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:43:35.198+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:43:35.209+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:43:35.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:43:35.213+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:43:35.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.089 seconds
[2024-12-16T18:44:05.643+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:44:05.644+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:44:05.644+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:44:05.644+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:44:05.648+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:44:05.646+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:44:05.648+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:44:05.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.024 seconds
[2024-12-16T18:44:36.254+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:44:36.255+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:44:36.255+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:44:36.255+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:44:36.260+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:44:36.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:44:36.260+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:44:36.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.020 seconds
[2024-12-16T18:45:53.572+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:45:53.578+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:45:53.580+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:45:53.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:45:53.609+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:45:53.603+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:45:53.618+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:45:53.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.114 seconds
[2024-12-16T18:46:35.755+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:46:35.758+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:46:35.759+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:46:35.759+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:46:35.768+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:46:35.766+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:46:35.769+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:46:35.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.054 seconds
[2024-12-16T18:47:06.038+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:47:06.039+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:47:06.040+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:47:06.040+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:47:06.047+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:47:06.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:47:06.047+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:47:06.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.028 seconds
[2024-12-16T18:47:36.687+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:47:36.687+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:47:36.688+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:47:36.688+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:47:36.692+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:47:36.691+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:47:36.692+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:47:36.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.024 seconds
[2024-12-16T18:48:07.679+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:48:07.679+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:48:07.680+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:48:07.680+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:48:07.684+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:48:07.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:48:07.684+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:48:07.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.021 seconds
[2024-12-16T18:48:38.425+0000] {processor.py:157} INFO - Started process (PID=69) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:48:38.426+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:48:38.426+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:48:38.426+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:48:38.430+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:48:38.429+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:48:38.431+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:48:38.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.021 seconds
[2024-12-16T18:49:08.933+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:49:08.935+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:49:08.935+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:49:08.935+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:49:08.942+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:49:08.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:49:08.944+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:49:08.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.043 seconds
[2024-12-16T18:49:39.943+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:49:39.944+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/scripts/pyspark_consumer2.py for tasks to queue
[2024-12-16T18:49:39.945+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:49:39.944+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:49:39.949+0000] {logging_mixin.py:150} INFO - [2024-12-16T18:49:39.948+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/pyspark_consumer2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/pyspark_consumer2.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-12-16T18:49:39.950+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/pyspark_consumer2.py
[2024-12-16T18:49:39.962+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/pyspark_consumer2.py took 0.021 seconds
